# Generated by Django 3.2.7 on 2021-10-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(db_index=True, max_length=30)),
                ('armor', models.CharField(blank=True, max_length=30, null=True)),
                ('descriptions', models.TextField()),
                ('element', models.CharField(blank=True, max_length=30, null=True)),
                ('exp', models.IntegerField(blank=True, default=0, null=True)),
                ('exp_class', models.IntegerField(blank=True, default=0, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('rank', models.CharField(blank=True, max_length=15, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('accuracy', models.IntegerField(blank=True, default=0, null=True)),
                ('matk_max', models.IntegerField(blank=True, default=0, null=True)),
                ('matk_min', models.IntegerField(blank=True, default=0, null=True)),
                ('patk_max', models.IntegerField(blank=True, default=0, null=True)),
                ('patk_min', models.IntegerField(blank=True, default=0, null=True)),
                ('blockpen', models.IntegerField(blank=True, default=0, null=True)),
                ('block', models.IntegerField(blank=True, default=0, null=True)),
                ('critdmg', models.IntegerField(blank=True, default=0, null=True)),
                ('critdef', models.IntegerField(blank=True, default=0, null=True)),
                ('critrate', models.IntegerField(blank=True, default=0, null=True)),
                ('mdef', models.IntegerField(blank=True, default=0, null=True)),
                ('pdef', models.IntegerField(blank=True, default=0, null=True)),
                ('eva', models.IntegerField(blank=True, default=0, null=True)),
                ('hp', models.IntegerField(blank=True, default=0, null=True)),
                ('stat_dex', models.IntegerField(blank=True, default=0, null=True)),
                ('stat_int', models.IntegerField(blank=True, default=0, null=True)),
                ('stat_spr', models.IntegerField(blank=True, default=0, null=True)),
                ('stat_str', models.IntegerField(blank=True, default=0, null=True)),
                ('stat_con', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(blank=True, default=0, null=True)),
                ('qty_max', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_min', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items', verbose_name='monster_item_item')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monsters.monsters', verbose_name='monster_item_monster')),
            ],
        ),
    ]
