# Generated by Django 3.2.7 on 2021-10-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0002_auto_20211015_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=30)),
                ('cooldown', models.IntegerField(blank=True, null=True)),
                ('sfr', models.IntegerField(blank=True, null=True)),
                ('monsters', models.ManyToManyField(to='Monsters.Monsters')),
            ],
        ),
    ]
