# Generated by Django 3.2.7 on 2021-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0003_skill_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_monster',
            name='aar',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='skill_monster',
            name='hit_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
