# Generated by Django 3.2.9 on 2021-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0004_auto_20211016_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsters',
            name='id_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
