# Generated by Django 3.2.9 on 2021-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0005_alter_monsters_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsters',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
