# Generated by Django 3.2.9 on 2021-11-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0006_alter_monsters_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_monster',
            name='id_name',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='skill_monster',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
