# Generated by Django 3.2.6 on 2022-01-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0003_jobs_vaivora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(to='Jobs.Jobs')),
            ],
        ),
    ]
