# Generated by Django 3.2.7 on 2021-10-08 01:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('cooldown', models.IntegerField()),
                ('sp', models.IntegerField()),
                ('sfr', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('element', models.CharField(max_length=30)),
                ('max_lv', models.IntegerField(default=-1)),
                ('unlock', models.IntegerField(default=0)),
                ('overheat', models.IntegerField(default=0)),
                ('captionratio1', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('captionratio2', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('captionratio3', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('captiontime', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('skillsr', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('spenditemcount', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('spendsp', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('spendpoison', django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=220, null=True, size=10)),
                ('other', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=153, null=True, size=3)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs', verbose_name='job')),
                ('stance', models.ManyToManyField(blank=True, null=True, to='Skills.Stance')),
            ],
        ),
    ]
