# Generated by Django 3.2.7 on 2021-10-08 07:01

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='job',
        ),
        migrations.AddField(
            model_name='skills',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='captionratio1',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='captionratio2',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='captionratio3',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='captiontime',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='sfr',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillsr',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='spenditemcount',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='spendpoison',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='spendsp',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='stance',
            field=models.ManyToManyField(to='Skills.Stance'),
        ),
    ]
