# Generated by Django 3.2.7 on 2021-10-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0003_rename_jobs_skills_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
