# Generated by Django 3.2.8 on 2021-10-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0005_auto_20211015_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='id_name',
            field=models.CharField(max_length=50),
        ),
    ]
