# Generated by Django 3.2.8 on 2021-10-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0006_alter_skills_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='stance',
        ),
        migrations.AddField(
            model_name='skills',
            name='stance',
            field=models.TextField(default='all'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stance',
        ),
    ]
