# Generated by Django 3.2.8 on 2021-10-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0007_auto_20211027_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_riding',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
