# Generated by Django 3.2.9 on 2021-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0008_skills_is_riding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='id_name',
            field=models.CharField(max_length=100),
        ),
    ]
