# Generated by Django 3.2.9 on 2021-12-05 14:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0009_alter_skills_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='cooldown_lv',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=220, null=True, size=10),
        ),
    ]
