# Generated by Django 3.2.6 on 2022-01-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buffs', '0005_auto_20211116_1000'),
        ('Skills', '0010_skills_cooldown_lv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField()),
                ('duration', models.FloatField()),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffs.buffs')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skills.skills')),
            ],
        ),
    ]
