# Generated by Django 3.2.6 on 2022-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0011_buff_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='is_riding',
            field=models.IntegerField(),
        ),
    ]
