# Generated by Django 3.2.6 on 2021-11-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(db_index=True, max_length=100)),
                ('descriptions', models.TextField()),
                ('desc_title', models.TextField()),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
