# Generated by Django 3.2.9 on 2021-12-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='name',
            field=models.TextField(),
        ),
    ]
