# Generated by Django 3.2.9 on 2021-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_auto_20211015_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='id_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maps',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
