# Generated by Django 3.2.9 on 2021-11-16 07:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0003_auto_20211116_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_npc',
            name='positions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=30), max_length=630, size=20),
        ),
    ]
