# Generated by Django 3.2.7 on 2021-10-08 01:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_equipment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(db_index=True, max_length=30)),
                ('cooldown', models.IntegerField(blank=True, default=None, null=True)),
                ('descriptions', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('tradability', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('type', models.CharField(blank=True, db_index=True, default=None, max_length=15, null=True)),
                ('grade', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('icon', models.CharField(blank=True, default=None, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
                ('text', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
                ('type_card', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('icon', models.CharField(blank=True, default=None, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
            ],
        ),
        migrations.CreateModel(
            name='Cubes',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
                ('anvil_atk', django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41)),
                ('anvil_def', django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41)),
                ('anvil_price', django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41)),
                ('durability', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('potential', models.IntegerField(blank=True, null=True)),
                ('requiredClass', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sockets_limit', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('matk', models.IntegerField(blank=True, null=True)),
                ('patk', models.IntegerField(blank=True, null=True)),
                ('patk_max', models.IntegerField(blank=True, null=True)),
                ('mdef', models.IntegerField(blank=True, null=True)),
                ('pdef', models.IntegerField(blank=True, null=True)),
                ('transcend_price', django_mysql.models.ListCharField(models.IntegerField(), max_length=30, size=10)),
                ('type_attack', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type_equipment', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('unidentified', models.BooleanField()),
                ('unidentifiedRandom', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Recipe_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items', verbose_name='target')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.recipes', verbose_name='recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Recipe_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items', verbose_name='recipe_material')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.recipes', verbose_name='recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Collection_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items', verbose_name='collection_material')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.collections', verbose_name='collection')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Collection_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_stat', models.CharField(max_length=30)),
                ('bonus_val', models.CharField(max_length=30)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.collections', verbose_name='collection')),
            ],
        ),
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Items.items')),
                ('skill', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skills.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_stat', models.CharField(max_length=30)),
                ('bonus_val', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.equipments', verbose_name='Equipment_Bonus')),
            ],
        ),
    ]
