# Generated by Django 3.2.7 on 2021-10-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20211015_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_Maps',
        ),
    ]
