# Generated by Django 3.2.9 on 2021-11-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_alter_items_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='type_card',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
