# Generated by Django 3.2.9 on 2021-11-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_alter_cards_type_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
