# Generated by Django 3.2.9 on 2021-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0010_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
