# Generated by Django 3.2.6 on 2021-12-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0012_auto_20211116_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goddess_Reinforce_Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField()),
                ('anvil', models.IntegerField()),
                ('chance', models.FloatField()),
                ('addatk', models.IntegerField(default=0)),
                ('addacc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goddess_Reinforce_Mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField()),
                ('mat_count', models.IntegerField()),
                ('anvil', models.IntegerField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items')),
            ],
        ),
    ]
