# Generated by Django 3.2.6 on 2021-12-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0013_goddess_reinforce_chance_goddess_reinforce_mat'),
    ]

    operations = [
        migrations.AddField(
            model_name='goddess_reinforce_chance',
            name='eq_type',
            field=models.CharField(default='armor', max_length=20),
        ),
    ]
