# Generated by Django 3.2.6 on 2021-12-23 08:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0015_auto_20211222_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='anvil_price',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=615, null=True, size=41),
        ),
    ]
