# Generated by Django 3.2.6 on 2021-12-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0017_auto_20211224_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_Type',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='transcend_price',
        ),
    ]
