# Generated by Django 3.2.6 on 2021-12-29 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0018_auto_20211229_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='Items.items', verbose_name='target'),
        ),
        migrations.DeleteModel(
            name='Item_Recipe_Target',
        ),
    ]
