# Generated by Django 3.2.6 on 2022-01-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0019_auto_20211229_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
