# Generated by Django 3.2.6 on 2022-01-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0020_auto_20220104_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_reinf',
            name='anvil',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eq_tc',
            name='tc',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='goddess_reinforce_chance',
            name='anvil',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='goddess_reinforce_chance',
            name='lv',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='goddess_reinforce_mat',
            name='anvil',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='goddess_reinforce_mat',
            name='lv',
            field=models.IntegerField(db_index=True),
        ),
    ]
