# Generated by Django 3.2.6 on 2022-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0021_auto_20220106_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='model',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
