# Generated by Django 3.2.6 on 2022-02-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0022_equipments_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_uuid', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serverid', models.IntegerField(db_index=True)),
                ('crawl_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.crawl_info')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionType', models.TextField()),
                ('optionValue', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.goods')),
            ],
        ),
    ]
