# Generated by Django 3.2.6 on 2022-02-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='serverid',
        ),
        migrations.AddField(
            model_name='crawl_info',
            name='serverid',
            field=models.IntegerField(db_index=True, default=1001),
            preserve_default=False,
        ),
    ]
