# Generated by Django 3.2.6 on 2022-02-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20220203_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='uid',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
