# Generated by Django 3.2.6 on 2022-02-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_goods_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl_info',
            name='date',
        ),
    ]
