# Generated by Django 3.2.6 on 2022-02-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0022_equipments_model'),
        ('Market', '0005_remove_crawl_info_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('serverid', models.IntegerField(db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('crawl_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.crawl_summary')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items')),
            ],
        ),
    ]
