# Generated by Django 3.2.6 on 2022-02-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_crawl_summary_goods_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods_summary',
            old_name='crawl_info',
            new_name='crawl_summary',
        ),
    ]
