# Generated by Django 3.2.7 on 2021-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(db_index=True, max_length=30)),
                ('id_name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('job_tree', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('is_starter', models.BooleanField(default=False)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
