# Generated by Django 3.2.6 on 2021-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffs',
            name='keyword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
