# Generated by Django 3.2.6 on 2021-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffs', '0002_buffs_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffs',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buffs',
            name='id_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buffs',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buffs',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
