# Generated by Django 3.2.9 on 2021-11-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffs', '0003_auto_20211102_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffs',
            name='applytime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
