# Generated by Django 3.2.6 on 2022-01-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffs', '0005_auto_20211116_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffs',
            name='id_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
