# Generated by Django 3.2.8 on 2021-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attributes', '0002_auto_20211015_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
