from django import template
register = template.Library()
from django.conf import settings

translation ={
	"itos" : {
		"home" 			: "Home",
		"items" 		: "Items",
		"npcs" 			: "NPCs",
		"maps"			: "Maps",
		"jobs" 			: "Classes",
		"skills"		: "Skills",
		"attributes" 	: "Attributes",
		"attribute" 	: "Attribute",
		"buffs"			: "Buffs",
		"planner"		: "Planner",
		'is toggleable'	: 'is toggleable',
		'max level'		: 'Max Level',
		'skill name' 	: 'Skill Name',
		'job'			: "Class",
		'visual' 		: "Visual",
		'associated skills' : 'Associated skills',
		'results' 		: "Results",
		'name' 			: 'Name',
		'description' 	: 'Description',
		'keyword'		: 'Keyword',
		'duration'		: 'Duration',
		'max stack'		: 'Max stack',
		'self remove' 	: 'Self remove',
		'group1'		: 'Group 1',
		'group2'		: 'Group 2',
		'group3'		: 'Group 3',
		'type'			: 'Type',
		'grade'			: 'Grade',
		'more'			: 'more',
		'race'			: 'Race',
		'elements'		: 'Attributes',
		'armor'			: 'Armor',
		"class tree"	: "Class Tree",
		'level'			: 'Lv',
		'archer'		: 'Archer',
		'cleric'		: 'Cleric',
		'scout'			: 'Scout',
		'swordman'		: 'Swordman',
		'normal'		: 'Normal',
		'magic'			: 'Magic',
		'rare'			: 'Rare',
		'unique'		: 'Unique',
		'legendary'		: 'Legendary',
		'goddess'		: 'Goddess',
		'trade'			: 'Trade',
		'weight'		: 'Weight',
		'durability'	: 'Durability',
		'potential'		: 'Potential',
		'patk'			: 'PATK',
		'matk'			: 'MATK',
		'pdef'			: 'PDEF',
		'mdef'			: 'MDEF',
		'anvil'			: 'Anvil',
		'bonus'			: 'Bonus',
		'gabija token'	: 'Gabija token',
		'scales'		: 'Scales',
		'chance'		: 'Chance',
		'price'			: 'Price',
		'total'			: 'Total',
		'transcend'		: 'Transcend',
		'chance'		: 'Chance',
		'produce'		: 'Produce',
		'materials'		: 'Materials',
		'refferences'	: 'Refferences',
		'crafted from'	: 'Crafted From',
		'collections'	: 'Collections',
		"dropped by" 	: "Dropped by" ,
		'dropped at'	: 'Dropped at',
		'population'	: 'Population',
	},

	"jtos" : {
		"home" 			: "ホーム",
		"items" 		: "アイテム",
		"npcs" 			: "NPCs",
		"maps"			: "マップ",
		"jobs" 			: "クラス",
		"skills"		: "スキル",
		"attributes" 	: "特性",
		"attribute" 	: "特性",
		"buffs"			: "バフ",
		"planner"		: "シミュレータ",
		'is toggleable'	: 'ｱｸﾃｨﾌﾞ型',
		'max level'		: '最大レベル ',
		'skill name'	: 'スキル名',
		'job'			: "クラス",
		'visual' 		: "ビジュアル",
		'associated skills' : '関連するスキル',
		'results' 		: "結果",
		'name' 			: '名前',
		'description' 	: '説明文',
		'keyword'		: 'キーワード',
		'duration'		: '期限',
		'max stack'		: '最大スタック',
		'self remove' 	: '自己取り外し可能',
		'group1'		: 'グループ 1',
		'group2'		: 'グループ 2',
		'group3'		: 'グループ 3',
		'type'			: 'タイプ',
		'grade'			: 'グレード',
		'more'			: '他',
		'race'			: '種族',
		'elements'		: '属性',
		'armor'			: '防御属性',
		"class tree"	: "クラスツリー ",
		'level'			: 'Lv',
		'archer'		: 'アーチャ',
		'cleric'		: 'クレリック',
		'scout'			: 'スカウト',
		'swordman'		: 'ソードマン',
		'wizard'		: 'ウイザード',
		'normal'		: '白',
		'magic'			: '青',
		'rare'			: '紫',
		'unique'		: '橙',
		'legendary'		: 'レジェンド',
		'goddess'		: '女神',
		'trade'			: 'トレード',
		'weight'		: '重量',
		'durability'	: '耐久性',
		'potential'		: '可能性',
		'patk'			: 'PATK',
		'matk'			: 'MATK',
		'pdef'			: 'PDEF',
		'mdef'			: 'MDEF',
		'anvil'			: 'アンビル',
		'bonus'			: 'ボーナス',
		'gabija token'	: 'ガビジャトークン',
		'scales'		: 'スケール',
		'chance'		: 'チャンス',
		'price'			: '価格',
		'total'			: '合計',
		'transcend'		: '超越',
		'chance'		: 'チャンス',
		'produce'		: 'プロデュース',
		'materials'		: '材料',
		'refferences'	: '参考',
		'crafted from'	: 'クラフト',
		'collections'	: 'コレクション',
		"dropped by" 	: "ドロップ" ,
		'dropped at'	: 'ドロップ',
		'population'	: '人口',
		'time respawn'	: 'タイムリスポーン',
		'rank'			: 'ランク',
		'drop'			: "ドロップ" ,
		'stance' 		: "スタンス",
		'riding'		: "ライディング",
		'effect' 		: '効果',
		"resp."			: 'リスポーン',
		'pop.'			: '人口',
		'max lv'		: '最大レベル ',
		"class"			: "クラス",
		"job tree"		: "クラスツリー ",
		'size'			: 'サイズ ',
		'demon'			: '悪魔',
		'beast'			: '獣',
		'mutant'		: '変異',
		'plant'			: '植物',
		'insect'		: '虫',
		'none'			: 'なし',
		'poison'		: '毒',
		'lightning'		: '雷',
		'fire'			: '火',
		'ice'			: '氷',
		'soul'			: '魂',
		'holy'			: '聖',
		'dark'			: '闇',
		'earth'			: '地',
		'melee'			: '近接',
		'cloth'			: 'クロース',
		'plate'			: 'プレート',
		'leather'		: 'レザー',
		'ghost'			: 'アストラル',
		'chain'			: '鎖',
		'misc'			: 'その他',
		'achievements'  : '業績',
		'title' 		: '報酬',
	}
}


@register.filter
def translate(value):
	region = settings.REGION 
	if (region in ['ktos', 'ktest']):
		region = 'itos'
	try:
		return translation[region][value.lower()]
	except:
		return value
